// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// broadcast_progress_update
void broadcast_progress_update(CharacterVector message, NumericVector percentage);
RcppExport SEXP rdotnetsamples_broadcast_progress_update(SEXP messageSEXP, SEXP percentageSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type message(messageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type percentage(percentageSEXP);
    broadcast_progress_update(message, percentage);
    return R_NilValue;
END_RCPP
}
// register_default_progress_handler
void register_default_progress_handler();
RcppExport SEXP rdotnetsamples_register_default_progress_handler() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    register_default_progress_handler();
    return R_NilValue;
END_RCPP
}
