# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

broadcast_progress_update <- function(message, percentage) {
    invisible(.Call('rdotnetsamples_broadcast_progress_update', PACKAGE = 'rdotnetsamples', message, percentage))
}

register_default_progress_handler <- function() {
    invisible(.Call('rdotnetsamples_register_default_progress_handler', PACKAGE = 'rdotnetsamples'))
}

